In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('athletes.csv')
df.head()

id            name nationality     sex       dob  height  weight  \
0  736041664  A Jesus Garcia         ESP    male  10/17/69    1.72    64.0   
1  532037425      A Lam Shin         KOR  female   9/23/86    1.68    56.0   
2  435962603     Aaron Brown         CAN    male   5/27/92    1.98    79.0   
3  521041435      Aaron Cook         MDA    male    1/2/91    1.83    80.0   
4   33922579      Aaron Gate         NZL    male  11/26/90    1.81    71.0   

       sport  gold  silver  bronze  
0  athletics     0       0       0  
1    fencing     0       0       0  
2  athletics     0       0       1  
3  taekwondo     0       0       0  
4    cycling     0       0       0

In [3]:
del df['dob'], df['id'], df['name']
df.head()

nationality     sex  height  weight      sport  gold  silver  bronze
0         ESP    male    1.72    64.0  athletics     0       0       0
1         KOR  female    1.68    56.0    fencing     0       0       0
2         CAN    male    1.98    79.0  athletics     0       0       1
3         MDA    male    1.83    80.0  taekwondo     0       0       0
4         NZL    male    1.81    71.0    cycling     0       0       0

In [4]:
df['nationality']=df['nationality'].astype(str)

In [5]:
df.isnull().sum()

nationality      0
sex              0
height         330
weight         659
sport            0
gold             0
silver           0
bronze           0
dtype: int64

In [6]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(missing_values = np.nan, strategy = 'mean')
imputer.fit(df.iloc[:, 2:4])
df.iloc[:, 2:4] = imputer.transform(df.iloc[:, 2:4])

In [7]:
df.isnull().sum()

nationality    0
sex            0
height         0
weight         0
sport          0
gold           0
silver         0
bronze         0
dtype: int64

In [8]:
print(len(df.nationality.unique()))
len(df.sport.unique())

207


28

In [9]:
X = df.iloc[:, 0:5].values
Y = df.iloc[:, [5,6,7]].values

In [10]:
X

array([['ESP', 'male', 1.72, 64.0, 'athletics'],
       ['KOR', 'female', 1.68, 56.0, 'fencing'],
       ['CAN', 'male', 1.98, 79.0, 'athletics'],
       ...,
       ['CHN', 'male', 1.85, 100.0, 'wrestling'],
       ['VIE', 'male', 1.6, 56.0, 'weightlifting'],
       ['RSA', 'male', 1.85, 70.0, 'athletics']], dtype=object)

In [11]:
X = X.transpose()

In [12]:
X[0]

array(['ESP', 'KOR', 'CAN', ..., 'CHN', 'VIE', 'RSA'], dtype=object)

In [13]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[0] = le.fit_transform(X[0])

In [14]:
X

array([[59, 102, 33, ..., 38, 202, 158],
       ['male', 'female', 'male', ..., 'male', 'male', 'male'],
       [1.72, 1.68, 1.98, ..., 1.85, 1.6, 1.85],
       [64.0, 56.0, 79.0, ..., 100.0, 56.0, 70.0],
       ['athletics', 'fencing', 'athletics', ..., 'wrestling',
        'weightlifting', 'athletics']], dtype=object)

In [15]:
le = LabelEncoder()
X[4] = le.fit_transform(X[4])

In [16]:
X

array([[59, 102, 33, ..., 38, 202, 158],
       ['male', 'female', 'male', ..., 'male', 'male', 'male'],
       [1.72, 1.68, 1.98, ..., 1.85, 1.6, 1.85],
       [64.0, 56.0, 79.0, ..., 100.0, 56.0, 70.0],
       [2, 9, 2, ..., 27, 26, 2]], dtype=object)

In [17]:
le = LabelEncoder()
X[1] = le.fit_transform(X[1])

In [18]:
X

array([[59, 102, 33, ..., 38, 202, 158],
       [1, 0, 1, ..., 1, 1, 1],
       [1.72, 1.68, 1.98, ..., 1.85, 1.6, 1.85],
       [64.0, 56.0, 79.0, ..., 100.0, 56.0, 70.0],
       [2, 9, 2, ..., 27, 26, 2]], dtype=object)

In [19]:
gender = df['sex'].values
nationality = df['nationality'].values
sports =  df['sport'].values

In [20]:
cat_gen = dict(zip(gender, X[1]))

In [21]:
cat_gen

{'male': 1, 'female': 0}

In [22]:
cat_nat = dict(zip(nationality, X[0]))
cat_spt = dict(zip(sports, X[4]))

In [23]:
cat_nat

{'ESP': 59,
 'KOR': 102,
 'CAN': 33,
 'MDA': 119,
 'NZL': 141,
 'AUS': 10,
 'USA': 198,
 'ETH': 61,
 'BRN': 27,
 'IOA': 86,
 'GBR': 68,
 'UZB': 199,
 'RSA': 158,
 'EGY': 56,
 'MAR': 116,
 'QAT': 155,
 'SUD': 175,
 'ALG': 2,
 'DEN': 51,
 'NED': 135,
 'DJI': 52,
 'SEN': 162,
 'CMR': 40,
 'ITA': 93,
 'NIG': 138,
 'SWE': 179,
 'GHA': 73,
 'AFG': 0,
 'AZE': 12,
 'KSA': 104,
 'BAN': 14,
 'NGR': 137,
 'RUS': 159,
 'IND': 85,
 'HUN': 83,
 'KAZ': 98,
 'BDI': 16,
 'ERI': 57,
 'POL': 151,
 'BRA': 26,
 'GEO': 70,
 'CZE': 50,
 'SEY': 163,
 'GAM': 67,
 'LTU': 113,
 'IRI': 87,
 'ROU': 157,
 'CUB': 48,
 'SLO': 167,
 'BAH': 13,
 'ARG': 6,
 'PUR': 154,
 'FRA': 64,
 'RWA': 160,
 'TOG': 188,
 'MDV': 120,
 'TUN': 191,
 'ISR': 91,
 'LAT': 106,
 'JOR': 96,
 'MAS': 117,
 'LIB': 111,
 'LBA': 107,
 'PLE': 148,
 'IRQ': 89,
 'TUR': 192,
 'VEN': 201,
 'JPN': 97,
 'TPE': 189,
 'KGZ': 100,
 'CHN': 38,
 'MEX': 121,
 'GRE': 74,
 'IRL': 88,
 'JAM': 95,
 'SUI': 176,
 'BAR': 15,
 'HON': 82,
 'ANG': 4,
 'GER': 72,
 'COL':

In [24]:
cat_data = [cat_nat, cat_gen, cat_spt]

In [25]:
cat_data

[{'ESP': 59,
  'KOR': 102,
  'CAN': 33,
  'MDA': 119,
  'NZL': 141,
  'AUS': 10,
  'USA': 198,
  'ETH': 61,
  'BRN': 27,
  'IOA': 86,
  'GBR': 68,
  'UZB': 199,
  'RSA': 158,
  'EGY': 56,
  'MAR': 116,
  'QAT': 155,
  'SUD': 175,
  'ALG': 2,
  'DEN': 51,
  'NED': 135,
  'DJI': 52,
  'SEN': 162,
  'CMR': 40,
  'ITA': 93,
  'NIG': 138,
  'SWE': 179,
  'GHA': 73,
  'AFG': 0,
  'AZE': 12,
  'KSA': 104,
  'BAN': 14,
  'NGR': 137,
  'RUS': 159,
  'IND': 85,
  'HUN': 83,
  'KAZ': 98,
  'BDI': 16,
  'ERI': 57,
  'POL': 151,
  'BRA': 26,
  'GEO': 70,
  'CZE': 50,
  'SEY': 163,
  'GAM': 67,
  'LTU': 113,
  'IRI': 87,
  'ROU': 157,
  'CUB': 48,
  'SLO': 167,
  'BAH': 13,
  'ARG': 6,
  'PUR': 154,
  'FRA': 64,
  'RWA': 160,
  'TOG': 188,
  'MDV': 120,
  'TUN': 191,
  'ISR': 91,
  'LAT': 106,
  'JOR': 96,
  'MAS': 117,
  'LIB': 111,
  'LBA': 107,
  'PLE': 148,
  'IRQ': 89,
  'TUR': 192,
  'VEN': 201,
  'JPN': 97,
  'TPE': 189,
  'KGZ': 100,
  'CHN': 38,
  'MEX': 121,
  'GRE': 74,
  'IRL': 88,
  'JA

In [26]:
X = X.transpose()
from sklearn.ensemble import RandomForestRegressor
ranForReg = RandomForestRegressor(n_estimators = 245, random_state = 40, max_depth = 14, min_samples_split = 10)
ranForReg.fit(X,Y)

RandomForestRegressor(max_depth=14, min_samples_split=10, n_estimators=245,
                      random_state=40)

In [27]:
def Inputs(country, gender, height, weight, sport):
    c = cat_data[0].get(country.upper())
    g = cat_data[1].get(gender.lower())
    s = cat_data[2].get(sport.lower())
    h = height
    w = weight
    list_data = [c,g,h,w,s]
    pred = ranForReg.predict([list_data])
    if pred[0][0] < 0.036:
        gold = 0
    elif pred[0][0] > 0.036 and pred[0][0] < 0.12:
        gold = 1
    elif pred[0][0] > 0.12 and pred[0][0] < 0.9:
        gold = 2
    elif pred[0][0] > 0.9:
        gold = '2+'
        
    if pred[0][1] < 0.3:
        silver = 0
    elif pred[0][1] > 0.3 and pred[0][1] < 0.5:
        silver = 1
    elif pred[0][1] > 0.5 :
        silver = '1+'
        
    if pred[0][2] < 0.21:
        bronze = 0
    elif pred[0][2] > 0.21 and pred[0][2] < 4.5:
        bronze = 1
    elif pred[0][2] > 4.5 :
        bronze = '1+'
    prediction = f'No. of Gold Medals: {gold} \nNo. of Silver Medals: {silver} \nNo. of Bronze Medal: {bronze}'
    return prediction

In [28]:
nation = input('Country: ')
gender = input('Gender: ')
height = float(input('Height: '))
weight = float(input('Weight: '))
sports = input('Sport: ')
print(Inputs(nation, gender, height, weight, sports))

Country: USA
Gender: male
Height: 178
Weight: 77
Sport: aquatics
No. of Gold Medals: 2 
No. of Silver Medals: 1 
No. of Bronze Medal: 0


In [29]:
import pickle

In [30]:
pickle.dump(ranForReg,open('Olympicpredictor.pk1','wb'))